
version: '3.8'

services:
  backend:
    build: ./
    restart: unless-stopped
    ports:
      - 5000:5000
    env_file: .docker.env
    volumes:
      - ./src/:/app/src/
    command: "poetry run python /app/src/main.py"
    # command: "sleep infinity"

  database:
    image: postgres:13
    env_file: .docker.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db:
